version: '3.9'

services:
  db:
    image: postgres
    container_name: astro_bot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env

  app:
    build: .
    container_name: astro_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/astro_bot/logs
      - ./alembic/versions:/astro_bot/alembic/versions
