version: '3.9'

services:
  db:
    image: postgres
    container_name: astro_bot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
    container_name: astro_bot
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["sh", "./docker/app.sh"]
    volumes:
      - ./logs:/astro_bot/logs
      - ./src/tg_bot/alembic/versions:/astro_bot/src/tg_bot/alembic/versions
    env_file:
      - .env
