version: '3.9'

services:
  app:
    build: .
    container_name: astro_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/astro_bot/logs
      - ./alembic/versions:/astro_bot/alembic/versions
