class ProfileCallback:
    CHANGE_PROFILE = "change_profile"
    CHANGE_DATA = "change_data"
    DELETE_PROFILE = "delete_profile"
    CHANGE_STATUS = "change_status"
    PROFILE_OPTION = "profile_chosen"
    ADD_PROFILE = "add_profile"
    CHANGE_TITLE = "change_title"
    CHANGE_BIRTH_DATE = "change_birth_date"
    CHANGE_BIRTH_TIME = "change_birth_time"
    CHANGE_BIRTH_LOCATION = "change_birth_location"
    CHANGE_LOCATION = "change_location"
