"""Initial migrations

Revision ID: b88c4c7cf78b
Revises: 3d7628a77782
Create Date: 2024-11-11 15:04:05.427026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88c4c7cf78b'
down_revision: Union[str, None] = '3d7628a77782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prediction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Prediction_id'), 'Prediction', ['id'], unique=True)
    op.add_column('Profile', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('Profile', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('Profile', sa.Column('creation_date', sa.DateTime(), nullable=False))
    op.add_column('Profile', sa.Column('title', sa.String(), nullable=False))
    op.add_column('Profile', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('Profile', sa.Column('birth_time', sa.Time(), nullable=False))
    op.add_column('Profile', sa.Column('birth_timezone', sa.String(), nullable=False))
    op.add_column('Profile', sa.Column('birth_latitude', sa.Float(), nullable=False))
    op.add_column('Profile', sa.Column('birth_longitude', sa.Float(), nullable=False))
    op.add_column('Profile', sa.Column('location_latitude', sa.Float(), nullable=False))
    op.add_column('Profile', sa.Column('location_longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Profile', 'location_longitude')
    op.drop_column('Profile', 'location_latitude')
    op.drop_column('Profile', 'birth_longitude')
    op.drop_column('Profile', 'birth_latitude')
    op.drop_column('Profile', 'birth_timezone')
    op.drop_column('Profile', 'birth_time')
    op.drop_column('Profile', 'birth_date')
    op.drop_column('Profile', 'title')
    op.drop_column('Profile', 'creation_date')
    op.drop_column('Profile', 'user_name')
    op.drop_column('Profile', 'user_id')
    op.drop_index(op.f('ix_Prediction_id'), table_name='Prediction')
    op.drop_table('Prediction')
    # ### end Alembic commands ###
